# Generated by Django 4.1.4 on 2022-12-28 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_rooms',
            name='location',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='available_rooms',
            name='payment_status',
            field=models.CharField(choices=[('N', 'None'), ('P', 'Processing'), ('C', 'Completed')], default='N', max_length=25),
        ),
        migrations.AddField(
            model_name='available_rooms',
            name='transaction',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
