# Generated by Django 4.1.4 on 2022-12-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_available_rooms_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_rooms',
            name='current_members',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='available_rooms',
            name='transaction',
            field=models.TextField(null=True),
        ),
    ]
