# Generated by Django 4.1.4 on 2022-12-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_available_rooms_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_rooms',
            name='transaction',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
