# Generated by Django 4.1.4 on 2022-12-28 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_available_rooms_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_rooms',
            name='transaction',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
