# Generated by Django 4.1.4 on 2022-12-28 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_alter_available_rooms_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='available_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('visits', models.IntegerField()),
                ('current_members', models.CharField(max_length=25, null=True)),
                ('rooms', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('location', models.JSONField(default=home.models.get_coordinate)),
                ('payment_status', models.CharField(choices=[('N', 'None'), ('P', 'Processing'), ('C', 'Completed')], default='N', max_length=25)),
                ('transaction', models.CharField(blank=True, max_length=255)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='available_rooms',
        ),
    ]
