# Generated by Django 4.1.4 on 2022-12-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_available_room_delete_available_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_room',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
